trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

jobs:
- job: Test
  displayName: 'Run Python Tests'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    submodules: true
    fetchDepth: 0

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: python -m unittest discover tests
    displayName: 'Run tests'
